+*In[20]:*+
[source, ipython3]
----
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import matplotlib as mpl
!pip install missingpy
plt.style.use("ggplot")
%matplotlib inline
----


+*Out[20]:*+
----
Requirement already satisfied: missingpy in c:\users\lenovo\anaconda3\lib\site-packages (0.2.0)
----


+*In[3]:*+
[source, ipython3]
----
df = pd.read_csv("UDPLag.csv", encoding='utf-8-sig')
----


+*In[4]:*+
[source, ipython3]
----
df.head()
----


+*Out[4]:*+
----
[cols=",,,,,,,,,,,,,,,,,,,,,",options="header",]
|===
| |Unnamed: 0 |Flow ID |Source IP |Source Port |Destination IP
|Destination Port |Protocol |Timestamp |Flow Duration |Total Fwd Packets
|... |Active Std |Active Max |Active Min |Idle Mean |Idle Std |Idle Max
|Idle Min |SimillarHTTP |Inbound |Label
|0 |50880 |172.16.0.5-192.168.50.4-35468-49856-17 |172.16.0.5 |35468
|192.168.50.4 |49856 |17 |2018-11-03 11:01:43.652742 |47 |2 |... |0.0
|0.0 |0.0 |0.0 |0.0 |0.0 |0.0 |0.0 |1.0 |UDP

|1 |83164 |172.16.0.5-192.168.50.4-44167-44225-17 |172.16.0.5 |44167
|192.168.50.4 |44225 |17 |2018-11-03 11:01:43.653107 |2 |2 |... |0.0
|0.0 |0.0 |0.0 |0.0 |0.0 |0.0 |0.0 |1.0 |UDP

|2 |49389 |172.16.0.5-192.168.50.4-36215-28771-17 |172.16.0.5 |36215
|192.168.50.4 |28771 |17 |2018-11-03 11:01:43.653383 |2 |2 |... |0.0
|0.0 |0.0 |0.0 |0.0 |0.0 |0.0 |0.0 |1.0 |UDP

|3 |34687 |172.16.0.5-192.168.50.4-44168-43679-17 |172.16.0.5 |44168
|192.168.50.4 |43679 |17 |2018-11-03 11:01:43.653386 |2 |2 |... |0.0
|0.0 |0.0 |0.0 |0.0 |0.0 |0.0 |0.0 |1.0 |UDP

|4 |87466 |172.16.0.5-192.168.50.4-52334-44960-17 |172.16.0.5 |52334
|192.168.50.4 |44960 |17 |2018-11-03 11:01:43.653387 |880701 |18 |...
|0.0 |0.0 |0.0 |0.0 |0.0 |0.0 |0.0 |0.0 |1.0 |UDP
|===

5 rows × 88 columns
----


+*In[5]:*+
[source, ipython3]
----
df.info()
----


+*Out[5]:*+
----
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45776 entries, 0 to 45775
Data columns (total 88 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Unnamed: 0                    45776 non-null  int64  
 1   Flow ID                       45776 non-null  object 
 2    Source IP                    45776 non-null  object 
 3    Source Port                  45776 non-null  int64  
 4    Destination IP               45776 non-null  object 
 5    Destination Port             45776 non-null  int64  
 6    Protocol                     45776 non-null  int64  
 7    Timestamp                    45776 non-null  object 
 8    Flow Duration                45776 non-null  int64  
 9    Total Fwd Packets            45776 non-null  int64  
 10   Total Backward Packets       45776 non-null  int64  
 11  Total Length of Fwd Packets   45776 non-null  float64
 12   Total Length of Bwd Packets  45776 non-null  float64
 13   Fwd Packet Length Max        45776 non-null  float64
 14   Fwd Packet Length Min        45776 non-null  float64
 15   Fwd Packet Length Mean       45776 non-null  float64
 16   Fwd Packet Length Std        45775 non-null  float64
 17  Bwd Packet Length Max         45775 non-null  float64
 18   Bwd Packet Length Min        45775 non-null  float64
 19   Bwd Packet Length Mean       45775 non-null  float64
 20   Bwd Packet Length Std        45775 non-null  float64
 21  Flow Bytes/s                  45775 non-null  float64
 22   Flow Packets/s               45775 non-null  float64
 23   Flow IAT Mean                45775 non-null  float64
 24   Flow IAT Std                 45775 non-null  float64
 25   Flow IAT Max                 45775 non-null  float64
 26   Flow IAT Min                 45775 non-null  float64
 27  Fwd IAT Total                 45775 non-null  float64
 28   Fwd IAT Mean                 45775 non-null  float64
 29   Fwd IAT Std                  45775 non-null  float64
 30   Fwd IAT Max                  45775 non-null  float64
 31   Fwd IAT Min                  45775 non-null  float64
 32  Bwd IAT Total                 45775 non-null  float64
 33   Bwd IAT Mean                 45775 non-null  float64
 34   Bwd IAT Std                  45775 non-null  float64
 35   Bwd IAT Max                  45775 non-null  float64
 36   Bwd IAT Min                  45775 non-null  float64
 37  Fwd PSH Flags                 45775 non-null  float64
 38   Bwd PSH Flags                45775 non-null  float64
 39   Fwd URG Flags                45775 non-null  float64
 40   Bwd URG Flags                45775 non-null  float64
 41   Fwd Header Length            45775 non-null  float64
 42   Bwd Header Length            45775 non-null  float64
 43  Fwd Packets/s                 45775 non-null  float64
 44   Bwd Packets/s                45775 non-null  float64
 45   Min Packet Length            45775 non-null  float64
 46   Max Packet Length            45775 non-null  float64
 47   Packet Length Mean           45775 non-null  float64
 48   Packet Length Std            45775 non-null  float64
 49   Packet Length Variance       45775 non-null  float64
 50  FIN Flag Count                45775 non-null  float64
 51   SYN Flag Count               45775 non-null  float64
 52   RST Flag Count               45775 non-null  float64
 53   PSH Flag Count               45775 non-null  float64
 54   ACK Flag Count               45775 non-null  float64
 55   URG Flag Count               45775 non-null  float64
 56   CWE Flag Count               45775 non-null  float64
 57   ECE Flag Count               45775 non-null  float64
 58   Down/Up Ratio                45775 non-null  float64
 59   Average Packet Size          45775 non-null  float64
 60   Avg Fwd Segment Size         45775 non-null  float64
 61   Avg Bwd Segment Size         45775 non-null  float64
 62   Fwd Header Length.1          45775 non-null  float64
 63  Fwd Avg Bytes/Bulk            45775 non-null  float64
 64   Fwd Avg Packets/Bulk         45775 non-null  float64
 65   Fwd Avg Bulk Rate            45775 non-null  float64
 66   Bwd Avg Bytes/Bulk           45775 non-null  float64
 67   Bwd Avg Packets/Bulk         45775 non-null  float64
 68  Bwd Avg Bulk Rate             45775 non-null  float64
 69  Subflow Fwd Packets           45775 non-null  float64
 70   Subflow Fwd Bytes            45775 non-null  float64
 71   Subflow Bwd Packets          45775 non-null  float64
 72   Subflow Bwd Bytes            45775 non-null  float64
 73  Init_Win_bytes_forward        45775 non-null  float64
 74   Init_Win_bytes_backward      45775 non-null  float64
 75   act_data_pkt_fwd             45775 non-null  float64
 76   min_seg_size_forward         45775 non-null  float64
 77  Active Mean                   45775 non-null  float64
 78   Active Std                   45775 non-null  float64
 79   Active Max                   45775 non-null  float64
 80   Active Min                   45775 non-null  float64
 81  Idle Mean                     45775 non-null  float64
 82   Idle Std                     45775 non-null  float64
 83   Idle Max                     45775 non-null  float64
 84   Idle Min                     45775 non-null  float64
 85  SimillarHTTP                  45775 non-null  float64
 86   Inbound                      45775 non-null  float64
 87   Label                        45775 non-null  object 
dtypes: float64(76), int64(7), object(5)
memory usage: 30.7+ MB
----


+*In[8]:*+
[source, ipython3]
----
df.shape
----


+*Out[8]:*+
----(45776, 88)----


+*In[9]:*+
[source, ipython3]
----
df.describe()
----


+*Out[9]:*+
----
[cols=",,,,,,,,,,,,,,,,,,,,,",options="header",]
|===
| |Unnamed: 0 |Source Port |Destination Port |Protocol |Flow Duration
|Total Fwd Packets |Total Backward Packets |Total Length of Fwd Packets
|Total Length of Bwd Packets |Fwd Packet Length Max |... |Active Mean
|Active Std |Active Max |Active Min |Idle Mean |Idle Std |Idle Max |Idle
Min |SimillarHTTP |Inbound
|count |45776.000000 |45776.000000 |45776.000000 |45776.000000
|4.577600e+04 |45776.000000 |45776.000000 |45776.000000 |45776.000000
|45776.000000 |... |4.577500e+04 |45775.000000 |4.577500e+04
|4.577500e+04 |4.577500e+04 |4.577500e+04 |4.577500e+04 |4.577500e+04
|45775.0 |45775.000000

|mean |57512.187566 |47061.845159 |33082.840987 |16.997116 |1.006426e+05
|3.685927 |0.003583 |1335.992638 |0.284341 |385.757187 |...
|2.797698e+02 |17.054369 |3.145583e+02 |2.727741e+02 |1.938712e+03
|9.148078e+01 |2.032518e+03 |1.822571e+03 |0.0 |0.999629

|std |32758.302415 |8259.201503 |18517.294120 |0.178079 |8.547252e+05
|2.916787 |0.320479 |1025.613129 |51.786659 |13.813623 |...
|4.754829e+04 |3622.112159 |4.834758e+04 |4.752392e+04 |1.386479e+05
|1.534938e+04 |1.465823e+05 |1.311199e+05 |0.0 |0.019268

|min |0.000000 |68.000000 |62.000000 |6.000000 |0.000000e+00 |1.000000
|0.000000 |0.000000 |0.000000 |0.000000 |... |0.000000e+00 |0.000000
|0.000000e+00 |0.000000e+00 |0.000000e+00 |0.000000e+00 |0.000000e+00
|0.000000e+00 |0.0 |0.000000

|25% |29163.250000 |39722.750000 |17299.000000 |17.000000 |1.000000e+00
|2.000000 |0.000000 |766.000000 |0.000000 |375.000000 |... |0.000000e+00
|0.000000 |0.000000e+00 |0.000000e+00 |0.000000e+00 |0.000000e+00
|0.000000e+00 |0.000000e+00 |0.0 |1.000000

|50% |57598.500000 |47361.500000 |32743.000000 |17.000000 |7.222250e+04
|4.000000 |0.000000 |1398.000000 |0.000000 |389.000000 |...
|0.000000e+00 |0.000000 |0.000000e+00 |0.000000e+00 |0.000000e+00
|0.000000e+00 |0.000000e+00 |0.000000e+00 |0.0 |1.000000

|75% |85843.500000 |54209.000000 |49061.000000 |17.000000 |1.088780e+05
|4.000000 |0.000000 |1438.000000 |0.000000 |393.000000 |...
|0.000000e+00 |0.000000 |0.000000e+00 |0.000000e+00 |0.000000e+00
|0.000000e+00 |0.000000e+00 |0.000000e+00 |0.0 |1.000000

|max |114279.000000 |63768.000000 |65531.000000 |17.000000 |7.234511e+07
|115.000000 |56.000000 |38572.000000 |10976.000000 |752.000000 |...
|9.930155e+06 |774949.479280 |9.930155e+06 |9.930155e+06 |1.040249e+07
|3.104260e+06 |1.424047e+07 |1.021846e+07 |0.0 |1.000000
|===

8 rows × 83 columns
----


+*In[10]:*+
[source, ipython3]
----
df.isnull()
----


+*Out[10]:*+
----
[cols=",,,,,,,,,,,,,,,,,,,,,",options="header",]
|===
| |Unnamed: 0 |Flow ID |Source IP |Source Port |Destination IP
|Destination Port |Protocol |Timestamp |Flow Duration |Total Fwd Packets
|... |Active Std |Active Max |Active Min |Idle Mean |Idle Std |Idle Max
|Idle Min |SimillarHTTP |Inbound |Label
|0 |False |False |False |False |False |False |False |False |False |False
|... |False |False |False |False |False |False |False |False |False
|False

|1 |False |False |False |False |False |False |False |False |False |False
|... |False |False |False |False |False |False |False |False |False
|False

|2 |False |False |False |False |False |False |False |False |False |False
|... |False |False |False |False |False |False |False |False |False
|False

|3 |False |False |False |False |False |False |False |False |False |False
|... |False |False |False |False |False |False |False |False |False
|False

|4 |False |False |False |False |False |False |False |False |False |False
|... |False |False |False |False |False |False |False |False |False
|False

|... |... |... |... |... |... |... |... |... |... |... |... |... |...
|... |... |... |... |... |... |... |...

|45771 |False |False |False |False |False |False |False |False |False
|False |... |False |False |False |False |False |False |False |False
|False |False

|45772 |False |False |False |False |False |False |False |False |False
|False |... |False |False |False |False |False |False |False |False
|False |False

|45773 |False |False |False |False |False |False |False |False |False
|False |... |False |False |False |False |False |False |False |False
|False |False

|45774 |False |False |False |False |False |False |False |False |False
|False |... |False |False |False |False |False |False |False |False
|False |False

|45775 |False |False |False |False |False |False |False |False |False
|False |... |True |True |True |True |True |True |True |True |True |True
|===

45776 rows × 88 columns
----


+*In[24]:*+
[source, ipython3]
----
import missingno as msno
[msno.matrix(df.iloc[: , n:n+20]) for n in list(range(0,len(df.columns),20))]
----


+*Out[24]:*+
----

    ---------------------------------------------------------------------------

    ModuleNotFoundError                       Traceback (most recent call last)

    <ipython-input-24-5f3fd1d659e4> in <module>
    ----> 1 import missingno as msno
          2 [msno.matrix(df.iloc[: , n:n+20]) for n in list(range(0,len(df.columns),20))]
    

    ModuleNotFoundError: No module named 'missingno'

----


+*In[25]:*+
[source, ipython3]
----
[df.iloc[: , n:n+20].isnull().sum() for n in list(range(0,len(df.columns),20))]
----


+*Out[25]:*+
----[Unnamed: 0                      0
 Flow ID                         0
  Source IP                      0
  Source Port                    0
  Destination IP                 0
  Destination Port               0
  Protocol                       0
  Timestamp                      0
  Flow Duration                  0
  Total Fwd Packets              0
  Total Backward Packets         0
 Total Length of Fwd Packets     0
  Total Length of Bwd Packets    0
  Fwd Packet Length Max          0
  Fwd Packet Length Min          0
  Fwd Packet Length Mean         0
  Fwd Packet Length Std          1
 Bwd Packet Length Max           1
  Bwd Packet Length Min          1
  Bwd Packet Length Mean         1
 dtype: int64,
  Bwd Packet Length Std    1
 Flow Bytes/s              1
  Flow Packets/s           1
  Flow IAT Mean            1
  Flow IAT Std             1
  Flow IAT Max             1
  Flow IAT Min             1
 Fwd IAT Total             1
  Fwd IAT Mean             1
  Fwd IAT Std              1
  Fwd IAT Max              1
  Fwd IAT Min              1
 Bwd IAT Total             1
  Bwd IAT Mean             1
  Bwd IAT Std              1
  Bwd IAT Max              1
  Bwd IAT Min              1
 Fwd PSH Flags             1
  Bwd PSH Flags            1
  Fwd URG Flags            1
 dtype: int64,
  Bwd URG Flags             1
  Fwd Header Length         1
  Bwd Header Length         1
 Fwd Packets/s              1
  Bwd Packets/s             1
  Min Packet Length         1
  Max Packet Length         1
  Packet Length Mean        1
  Packet Length Std         1
  Packet Length Variance    1
 FIN Flag Count             1
  SYN Flag Count            1
  RST Flag Count            1
  PSH Flag Count            1
  ACK Flag Count            1
  URG Flag Count            1
  CWE Flag Count            1
  ECE Flag Count            1
  Down/Up Ratio             1
  Average Packet Size       1
 dtype: int64,
  Avg Fwd Segment Size       1
  Avg Bwd Segment Size       1
  Fwd Header Length.1        1
 Fwd Avg Bytes/Bulk          1
  Fwd Avg Packets/Bulk       1
  Fwd Avg Bulk Rate          1
  Bwd Avg Bytes/Bulk         1
  Bwd Avg Packets/Bulk       1
 Bwd Avg Bulk Rate           1
 Subflow Fwd Packets         1
  Subflow Fwd Bytes          1
  Subflow Bwd Packets        1
  Subflow Bwd Bytes          1
 Init_Win_bytes_forward      1
  Init_Win_bytes_backward    1
  act_data_pkt_fwd           1
  min_seg_size_forward       1
 Active Mean                 1
  Active Std                 1
  Active Max                 1
 dtype: int64,
  Active Min     1
 Idle Mean       1
  Idle Std       1
  Idle Max       1
  Idle Min       1
 SimillarHTTP    1
  Inbound        1
  Label          1
 dtype: int64]----


+*In[27]:*+
[source, ipython3]
----
s = df.head(50)['Flow Bytes/s']/df.head(50)[' Flow Packets/s']
s
----


+*Out[27]:*+
----0     389.000000
1     393.000000
2     374.000000
3     393.000000
4     366.666667
5     349.500000
6     359.500000
7     401.000000
8     401.000000
9     375.000000
10    361.500000
11    342.666667
12    386.000000
13    369.000000
14    369.000000
15    375.000000
16    389.000000
17    386.000000
18    361.500000
19    349.500000
20    369.000000
21    349.500000
22    393.000000
23    361.500000
24    369.000000
25    383.000000
26    369.000000
27    369.000000
28    329.000000
29    393.000000
30    369.000000
31    362.100000
32    375.000000
33    348.000000
34    369.000000
35    389.000000
36    375.000000
37    369.000000
38    359.500000
39    369.000000
40    349.500000
41    367.333333
42    401.000000
43    369.000000
44    401.000000
45    369.000000
46    401.000000
47    369.000000
48    401.000000
49    383.000000
dtype: float64----


+*In[28]:*+
[source, ipython3]
----
df['Flow Bytes/s'].fillna(df[' Flow Packets/s']*440, inplace=True)
df.isna().sum().sum()
----


+*Out[28]:*+
----72----


+*In[29]:*+
[source, ipython3]
----
print(df.columns.tolist())
----


+*Out[29]:*+
----
['Unnamed: 0', 'Flow ID', ' Source IP', ' Source Port', ' Destination IP', ' Destination Port', ' Protocol', ' Timestamp', ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets', 'Total Length of Fwd Packets', ' Total Length of Bwd Packets', ' Fwd Packet Length Max', ' Fwd Packet Length Min', ' Fwd Packet Length Mean', ' Fwd Packet Length Std', 'Bwd Packet Length Max', ' Bwd Packet Length Min', ' Bwd Packet Length Mean', ' Bwd Packet Length Std', 'Flow Bytes/s', ' Flow Packets/s', ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max', ' Flow IAT Min', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std', ' Fwd IAT Max', ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean', ' Bwd IAT Std', ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags', ' Bwd PSH Flags', ' Fwd URG Flags', ' Bwd URG Flags', ' Fwd Header Length', ' Bwd Header Length', 'Fwd Packets/s', ' Bwd Packets/s', ' Min Packet Length', ' Max Packet Length', ' Packet Length Mean', ' Packet Length Std', ' Packet Length Variance', 'FIN Flag Count', ' SYN Flag Count', ' RST Flag Count', ' PSH Flag Count', ' ACK Flag Count', ' URG Flag Count', ' CWE Flag Count', ' ECE Flag Count', ' Down/Up Ratio', ' Average Packet Size', ' Avg Fwd Segment Size', ' Avg Bwd Segment Size', ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', ' Fwd Avg Packets/Bulk', ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk', ' Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', ' Subflow Fwd Bytes', ' Subflow Bwd Packets', ' Subflow Bwd Bytes', 'Init_Win_bytes_forward', ' Init_Win_bytes_backward', ' act_data_pkt_fwd', ' min_seg_size_forward', 'Active Mean', ' Active Std', ' Active Max', ' Active Min', 'Idle Mean', ' Idle Std', ' Idle Max', ' Idle Min', 'SimillarHTTP', ' Inbound', ' Label']
----


+*In[30]:*+
[source, ipython3]
----
target = df[' Label'][:].values
from collections import Counter
Counter(target)
----


+*Out[30]:*+
----Counter({'UDP': 45763, 'BENIGN': 12, nan: 1})----


+*In[31]:*+
[source, ipython3]
----
str(((target == 'BENIGN').sum()/len(target))*100)+"%"
----


+*Out[31]:*+
----'0.02621461027612723%'----


+*In[32]:*+
[source, ipython3]
----
from sklearn.preprocessing import LabelEncoder
----


+*In[33]:*+
[source, ipython3]
----
df[' Label'].replace('BENIGN', 0, inplace=True)
----


+*In[34]:*+
[source, ipython3]
----
df[' Label'].replace('DrDoS_DNS', 1, inplace=True)
----


+*In[35]:*+
[source, ipython3]
----
df[' Label'].value_counts()
----


+*Out[35]:*+
----UDP    45763
0         12
Name:  Label, dtype: int64----


+*In[36]:*+
[source, ipython3]
----
encodings=[x for x in df.columns if df[x].dtype=="object"]

le=LabelEncoder()

for col in encodings:
    if col in df.columns:
        i = df.columns.get_loc(col)
        df.iloc[:,i] = df.apply(lambda i:le.fit_transform(i.astype(str)), axis=0, result_type='expand')
----


+*In[37]:*+
[source, ipython3]
----
df.replace(np.inf, np.nan, inplace=True)
----


+*In[38]:*+
[source, ipython3]
----
df.columns
----


+*Out[38]:*+
----Index(['Unnamed: 0', 'Flow ID', ' Source IP', ' Source Port',
       ' Destination IP', ' Destination Port', ' Protocol', ' Timestamp',
       ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets',
       'Total Length of Fwd Packets', ' Total Length of Bwd Packets',
       ' Fwd Packet Length Max', ' Fwd Packet Length Min',
       ' Fwd Packet Length Mean', ' Fwd Packet Length Std',
       'Bwd Packet Length Max', ' Bwd Packet Length Min',
       ' Bwd Packet Length Mean', ' Bwd Packet Length Std', 'Flow Bytes/s',
       ' Flow Packets/s', ' Flow IAT Mean', ' Flow IAT Std', ' Flow IAT Max',
       ' Flow IAT Min', 'Fwd IAT Total', ' Fwd IAT Mean', ' Fwd IAT Std',
       ' Fwd IAT Max', ' Fwd IAT Min', 'Bwd IAT Total', ' Bwd IAT Mean',
       ' Bwd IAT Std', ' Bwd IAT Max', ' Bwd IAT Min', 'Fwd PSH Flags',
       ' Bwd PSH Flags', ' Fwd URG Flags', ' Bwd URG Flags',
       ' Fwd Header Length', ' Bwd Header Length', 'Fwd Packets/s',
       ' Bwd Packets/s', ' Min Packet Length', ' Max Packet Length',
       ' Packet Length Mean', ' Packet Length Std', ' Packet Length Variance',
       'FIN Flag Count', ' SYN Flag Count', ' RST Flag Count',
       ' PSH Flag Count', ' ACK Flag Count', ' URG Flag Count',
       ' CWE Flag Count', ' ECE Flag Count', ' Down/Up Ratio',
       ' Average Packet Size', ' Avg Fwd Segment Size',
       ' Avg Bwd Segment Size', ' Fwd Header Length.1', 'Fwd Avg Bytes/Bulk',
       ' Fwd Avg Packets/Bulk', ' Fwd Avg Bulk Rate', ' Bwd Avg Bytes/Bulk',
       ' Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets',
       ' Subflow Fwd Bytes', ' Subflow Bwd Packets', ' Subflow Bwd Bytes',
       'Init_Win_bytes_forward', ' Init_Win_bytes_backward',
       ' act_data_pkt_fwd', ' min_seg_size_forward', 'Active Mean',
       ' Active Std', ' Active Max', ' Active Min', 'Idle Mean', ' Idle Std',
       ' Idle Max', ' Idle Min', 'SimillarHTTP', ' Inbound', ' Label'],
      dtype='object')----


+*In[39]:*+
[source, ipython3]
----
import missingno as msno
[msno.matrix(df.iloc[: , n:n+20]) for n in list(range(0,len(df.columns),20))];
----


+*Out[39]:*+
----

    ---------------------------------------------------------------------------

    ModuleNotFoundError                       Traceback (most recent call last)

    <ipython-input-39-2842efe7469b> in <module>
    ----> 1 import missingno as msno
          2 [msno.matrix(df.iloc[: , n:n+20]) for n in list(range(0,len(df.columns),20))];
    

    ModuleNotFoundError: No module named 'missingno'

----


+*In[ ]:*+
[source, ipython3]
----

----
